// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250721130019_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Güçlü bir laptop",
                            ImageUrl = "laptop.jpg",
                            IsActive = true,
                            Name = "Laptop",
                            Price = 25000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Akıllı telefon",
                            ImageUrl = "telefon.jpg",
                            IsActive = true,
                            Name = "Telefon",
                            Price = 15000m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Mekanik klavye",
                            ImageUrl = "klavye.jpg",
                            IsActive = true,
                            Name = "Klavye",
                            Price = 1200m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Kablosuz mouse",
                            ImageUrl = "mouse.jpg",
                            IsActive = true,
                            Name = "Mouse",
                            Price = 800m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "4K monitör",
                            ImageUrl = "monitor.jpg",
                            IsActive = true,
                            Name = "Monitör",
                            Price = 5000m,
                            Stock = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
