// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250723083610_AddNewProducts")]
    partial class AddNewProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Apple M2 çipli 13 inç MacBook Pro",
                            ImageUrl = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400",
                            IsActive = true,
                            Name = "MacBook Pro",
                            Price = 45000m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "A17 Pro çipli akıllı telefon",
                            ImageUrl = "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400",
                            IsActive = true,
                            Name = "iPhone 15 Pro",
                            Price = 35000m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Kablosuz mekanik klavye",
                            ImageUrl = "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400",
                            IsActive = true,
                            Name = "Logitech MX Keys",
                            Price = 2500m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Kablosuz ergonomik mouse",
                            ImageUrl = "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400",
                            IsActive = true,
                            Name = "Logitech MX Master 3",
                            Price = 1800m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "34 inç 4K UltraWide monitör",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400",
                            IsActive = true,
                            Name = "LG UltraWide",
                            Price = 12000m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "12.9 inç iPad Pro M2 çipli",
                            ImageUrl = "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400",
                            IsActive = true,
                            Name = "iPad Pro",
                            Price = 28000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Gürültü engelleyici kablosuz kulaklık",
                            ImageUrl = "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=400",
                            IsActive = true,
                            Name = "AirPods Pro",
                            Price = 6500m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 8,
                            Aciklama = "GPS + Cellular akıllı saat",
                            ImageUrl = "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=400",
                            IsActive = true,
                            Name = "Apple Watch Series 9",
                            Price = 12500m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 9,
                            Aciklama = "Android flagship telefon",
                            ImageUrl = "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400",
                            IsActive = true,
                            Name = "Samsung Galaxy S24",
                            Price = 28000m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 10,
                            Aciklama = "Kablosuz gürültü engelleyici kulaklık",
                            ImageUrl = "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400",
                            IsActive = true,
                            Name = "Sony WH-1000XM5",
                            Price = 8500m,
                            Stock = 14
                        },
                        new
                        {
                            Id = 11,
                            Aciklama = "Intel i7 işlemcili ultrabook",
                            ImageUrl = "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400",
                            IsActive = true,
                            Name = "Dell XPS 13",
                            Price = 38000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 12,
                            Aciklama = "Hibrit oyun konsolu",
                            ImageUrl = "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
                            IsActive = true,
                            Name = "Nintendo Switch",
                            Price = 8500m,
                            Stock = 35
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
